/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oFYElYQym1o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function chek() {
  return (
    <div className="grid md:grid-cols-2 w-full max-w-6xl mx-auto">
      <div className="hidden md:block bg-muted overflow-hidden">
        <img src="/placeholder.svg" alt="Image" width={800} height={600} className="w-full h-full object-cover" />
      </div>
      <div className="mx-auto max-w-md space-y-6 p-4 md:p-0">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Regístrate</h1>
          <p className="text-muted-foreground">Ingresa tus datos para crear una cuenta</p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="full-name">Nombre completo</Label>
            <Input id="full-name" placeholder="Juan Pérez" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Correo electrónico</Label>
            <Input id="email" type="email" placeholder="juan@ejemplo.com" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Contraseña</Label>
            <Input id="password" type="password" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="confirm-password">Confirmar contraseña</Label>
            <Input id="confirm-password" type="password" required />
          </div>
          <div className="flex items-center space-x-2">
            <Checkbox id="terms" />
            <Label htmlFor="terms" className="text-sm font-medium leading-none">
              Acepto los términos y condiciones
            </Label>
          </div>
          <Button type="submit" className="w-full">
            Registrarse
          </Button>
          <div className="text-center text-sm">
            ¿Ya tienes una cuenta?{" "}
            <Link href="#" className="underline" prefetch={false}>
              Inicia sesión
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
